#!/usr/bin/python3
import os
import subprocess

def getClipboardData():

    p = subprocess.Popen(['pbpaste'], stdout=subprocess.PIPE)

    retcode = p.wait()

    data = p.stdout.read()

    return data.decode("utf-8")

def setClipboardData(data):

    p = subprocess.Popen(['pbcopy'], stdin=subprocess.PIPE)

    p.stdin.write(data)

    p.stdin.close()

    p.communicate()

curl_code = getClipboardData()
curl_code = curl_code.replace('"', '\\\"')

python_code = os.popen('curlconverter -l python "' + curl_code + '"').read()

setClipboardData(python_code.encode())
